module.exports = {
  serverBuildTarget: 'vercel',
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === 'development' ? undefined : './server.js',
  ignoredRouteFiles: ['.*'],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "api/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    'remark-toc',
    // Needed for remark-toc and Remix
    'mdast-util-toc',
    'mdast-util-to-string',
    'unist-util-visit',
    'unist-util-visit-parents',
    'unist-util-is',

    // Needed for remark-gfm and Remix
    'remark-gfm',
    'micromark-extension-gfm',
    'micromark-util-combine-extensions',
    'micromark-util-chunked',
    'micromark-extension-gfm-autolink-literal',
    'micromark-util-character',
    'micromark-extension-gfm-footnote',
    'micromark-core-commonmark',
    'micromark-factory-space',
    'micromark-util-normalize-identifier',
    'micromark-extension-gfm-strikethrough',
    'micromark-util-classify-character',
    'micromark-util-resolve-all',
    'micromark-extension-gfm-table',
    'micromark-extension-gfm-tagfilter',
    'micromark-extension-gfm-task-list-item',
    'mdast-util-gfm',
    'mdast-util-gfm-autolink-literal',
    'ccount',
    'mdast-util-find-and-replace',
    'mdast-util-gfm-footnote',
    'mdast-util-to-markdown/lib/util/association.js',
    'mdast-util-to-markdown/lib/util/container-flow.js',
    'mdast-util-to-markdown/lib/util/indent-lines.js',
    'mdast-util-to-markdown/lib/util/safe.js',
    'mdast-util-to-markdown/lib/util/track.js',
    'mdast-util-to-markdown/lib/util/container-phrasing.js',
    'mdast-util-to-markdown/lib/handle/inline-code.js',
    'mdast-util-to-markdown/lib/handle/list-item.js',
    'mdast-util-gfm-strikethrough',
    'mdast-util-gfm-table',
    'micromark-util-decode-string',
    'decode-named-character-reference',
    'character-entities',
    'micromark-util-decode-numeric-character-reference',
    'markdown-table',
    'mdast-util-gfm-task-list-item',

    // Needed for rehype-slug and Remix
    'rehype-slug',
    'hast-util-has-property',
    'hast-util-heading-rank',
    'hast-util-to-string',
  ],
}
